HEALTH_CONTEXT_CHOICES = [
    ('agoraphobia', 'Agorafobia'),
    ('anxiety', 'Ansiedad'),
    ('social_anxiety', 'Ansiedad social'),
    ('panic_attacks', 'Ataques de pánico'),
    ('autism', 'Autismo / espectro autista'),
    ('burnout', 'Burnout / agotamiento'),
    ('brain_injury', 'Daño cerebral adquirido'),
    ('depression', 'Depresión'),
    ('diabetes', 'Diabetes'),
    ('learning_disability', 'Dificultad de aprendizaje'),
    ('hearing_disability', 'Discapacidad auditiva'),
    ('physical_disability', 'Discapacidad física o movilidad reducida'),
    ('intellectual_disability', 'Discapacidad intelectual'),
    ('visual_disability', 'Discapacidad visual'),
    ('pain_fatigue', 'Dolor crónico o fatiga'),
    ('grief', 'Duelo'),
    ('chronic_illness', 'Enfermedad crónica'),
    ('rare_disease', 'Enfermedad rara'),
    ('epilepsy', 'Epilepsia'),
    ('fibromyalgia', 'Fibromialgia'),
    ('specific_phobia', 'Fobia específica'),
    ('hypochondria', 'Hipocondría / aprensión por la salud'),
    ('insomnia', 'Insomnio'),
    ('cardiorespiratory_condition', 'Problema cardiorrespiratorio'),
    ('psychosis', 'Psicosis o esquizofrenia'),
    ('adhd', 'TDAH'),
    ('ocd', 'TOC'),
    ('bipolar', 'Trastorno bipolar'),
    ('eating_disorder', 'Trastorno de la conducta alimentaria'),
    ('speech_language_disorder', 'Trastorno del habla o lenguaje'),
    ('ptsd', 'Trauma / TEPT'),
    ('other', 'Otra situación'),
    ('prefer_not_detail', 'Prefiero no detallarlo'),
]

HEALTH_CONTEXT_LABELS = dict(HEALTH_CONTEXT_CHOICES)
