# Generated by Django 4.2.22 on 2026-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='health_context',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accessibility_visibility',
            field=models.CharField(choices=[('private', 'Solo yo'), ('connections', 'Conexiones'), ('public', 'Visible en mi perfil')], default='public', max_length=20),
        ),
    ]
