# Generated by Django 4.2.22 on 2026-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilephoto_datingaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='orientation',
            field=models.CharField(blank=True, choices=[('heterosexual', 'Heterosexual'), ('homosexual', 'Homosexual'), ('bisexual', 'Bisexual'), ('pansexual', 'Pansexual'), ('asexual', 'Asexual'), ('questioning', 'En duda'), ('other', 'Otra'), ('prefer_not_say', 'Prefiero no decirlo')], max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('woman', 'Mujer'), ('man', 'Hombre'), ('non_binary', 'No binario'), ('other', 'Otro'), ('prefer_not_say', 'Prefiero no decirlo')], max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoker',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('sometimes', 'A veces'), ('yes', 'Si'), ('prefer_not_say', 'Prefiero no decirlo')], max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
