# Generated by Django 4.2.22 on 2026-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_birth_date_profile_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dating_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
