# Generated by Django 4.2.22 on 2026-06-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datingaction',
            name='action',
            field=models.CharField(choices=[('like', 'Solicitar conectar'), ('pass', 'Pasar')], max_length=10),
        ),
    ]
