# Generated by Django 4.2.22 on 2026-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_blockedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='smoker',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('sometimes', 'A veces'), ('yes', 'Sí'), ('prefer_not_say', 'Prefiero no decirlo')], max_length=24),
        ),
    ]
