# Generated by Django 4.2.22 on 2026-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_smoker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='people_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
