# Generated by Django 4.2.22 on 2026-06-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('messaging', '0004_panelnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='community.plan'),
        ),
    ]
