# Generated by Django 4.2.22 on 2026-06-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_group_publication_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='link_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='link_title',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
